### ISSUE TITLE
android 7.0  搜索不到设备

### ISSUE THREAD

**Issue by sunkang23** [hubing8658/UPnP-DLNA-Demo#2]

**Comment by hubing8658** [comment]
具体现象是什么，我手头没有7.0的设备，目前无法分析是哪里的原因，模拟跟主机不在同一个网段，没法调试。

**Comment by muyu1016** [comment]
遇到同样的问题，已解决。代码中的Cling库版本为2.0.1，换成2.1.1就好了。

**Comment by hubing8658** [comment]
感谢反馈，我抽时间更新下Cling的库。

**Comment by hubing8658** [comment]
@sunkang23 已经更新了cling库，由于我这没有7.0的系统的手机，麻烦验证下，谢谢！
