### ISSUE TITLE
如何推送网络视频URL到电视端播放？

### ISSUE THREAD

**Issue by icemy** [hubing8658/UPnP-DLNA-Demo#3]
使用demo里面的SetAVTransportURI方法，返回是success，但是电视端没有任何反应。

**Comment by liaohuyu** [comment]
@hubing8658 同问

**Comment by liaohuyu** [comment]
@icemy 老铁你搞定在线播放投屏了么？

**Comment by liaohuyu** [comment]
知道了。public void setPlayUri(String url) {
		upnpBiz.execute(new SetAVTransportURI(instanceId, serviceAVT, url,
				null) {

			@Override
			public void failure(ActionInvocation invocation,
								UpnpResponse operation, String defaultMsg) {
				LogUtil.d(TAG, "setPlayUri failure:" + defaultMsg);
			}

			@Override
			public void onSuccess(String defaultMsg) {
				LogUtil.d(TAG, "SetAVTransportURI successed:" + defaultMsg);
				Message msg = Message.obtain(handler);
				msg.what = MediaControlWhat.SET_AVTRANSPORT_URI;
				msg.arg1 = SUCCESS;
				msg.sendToTarget();
			}
		});
	}，再封装个这个就行了。

**Comment by hubing8658** [comment]
这个应该要查看下电视的接口文档，确认电视是否支持这个接口，如果支持，调用SetAVTransportURI就可以了，这个和音乐、图片等是一样的，设置一个地址过去，电视自己去下拉，而app只是相当于一个摇控器

**Comment by liaohuyu** [comment]
了解  感谢~~

**Comment by liaohuyu** [comment]
@hubing8658 老铁 能加个好友么？Q：676057988

**Comment by hubing8658** [comment]
@liaohuyu 可以的，但是公司网络上不了QQ，很少在线了。这是我qq:305705722

**Comment by BruceLing** [comment]
请问是否可以实现多台（如两台）手机同时投屏到一个屏幕上（如电视屏幕）？如何实现？
