### ISSUE TITLE
请问是否可以实现多台（如两台）手机同时投屏到一个屏幕上（如电视屏幕）？如何实现？

### ISSUE THREAD

**Issue by BruceLing** [hubing8658/UPnP-DLNA-Demo#4]

**Comment by hubing8658** [comment]
这个是不支持直接投屏的，只能给你个实现的思路，使用发现设备协议，查找电视中的DMR、DMP能力，电视端可以通过分屏功能，开启两个DMR或者DMP，然后手机作为服务端，选择其中一个向其推流，应该是可以实现你想要的这种效果的。

**Comment by BruceLing** [comment]
好的，多谢！
